### ISSUE TITLE
發文者也要插旗

### ISSUE THREAD

**Issue by FlandreDaisuki** [osk2/ptt-comment-flag#11]
**這個功能是想要解決你的什麼問題？**
像是[這篇](https://www.ptt.cc/bbs/Gossiping/M.1536188697.A.CD7.html)據說是第一篇風向文，發文者 IP 現在用 whois 也能查到是中國北京

**你的想法/建議是？**
插旗

**其他相關資訊**
![_001](https://user-images.githubusercontent.com/5981459/45585449-fa074680-b916-11e8-981e-b1b7376ead24.png)

**Comment by FlandreDaisuki** [comment]
阿 發現跟 #3 重複了

**Comment by osk2** [comment]
這個我也想做很久了，不過發文者的 IP 有點難抓一直懶得處理 🤦‍♂️
