### ISSUE TITLE
Firefox 版本呢（敲碗）

### ISSUE THREAD

**Issue by brlin-tw** [osk2/ptt-comment-flag#2]
如題

**Comment by osk2** [comment]
好啦，有時間再來研究QQ

如果有人要發PR的話，可以的喔

**Comment by FlandreDaisuki** [comment]
#7

**Comment by osk2** [comment]
讚讚讚這招不錯

不過我用的是 yarn，看是要砍掉package-lock.json還是重新用yarn跑一次再commit

**Comment by osk2** [comment]
Resolved in 08a6fb3b5882ffb70e846611feccbe93f4470fbc.

Firefox version is now available at [Firefox Add-ons](https://addons.mozilla.org/zh-TW/firefox/addon/%E5%85%AB%E5%8D%A6%E6%8F%92ip/) 🎉
